#! /bin/bash

UID_LENGTH=8

new_uid () {
    env LC_CTYPE=C tr -dc "a-zA-Z0-9" < /dev/urandom | head -c $UID_LENGTH
}

if [ $# -ne 2 ] ; then
    echo "Usage: $0 <dir> <project-name>"
fi

cd $1

PROJ_PATH=$(ls | grep ".\{$UID_LENGTH\}-$2\$")
if [ -z "$PROJ_PATH" ]; then
    PROJ_UID="$(new_uid)"
    PROJ_PATH="$PROJ_UID-$2"
    while [ -d "$PROJ_PATH" ]; do
        PROJ_UID="$(new_uid)"
        PROJ_PATH="$PROJ_UID-$2"
    done
    mkdir "$PROJ_PATH"
fi
echo "$PROJ_PATH"
