#! /bin/bash

UID_LENGTH=8
ME=`basename "$0"`

new_uid () {
    env LC_CTYPE=C tr -dc "a-zA-Z0-9" < /dev/urandom | head -c $UID_LENGTH
}

usage () {
    echo "Usage: "
    echo "  $ME find <dir> <project-name>"
    echo "  $ME init <git_dir> <project-name>"
    echo ""
    echo "$1"
    exit 1
}
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
POST_RECEIVE="$DIR/post-receive"

if [ $# -ne 3 ] ; then
    usage "Missing command."
fi

if [ "$1" = "find" ]; then

    cd $2

    PROJ_PATH=$(ls | grep ".\{$UID_LENGTH\}-$3\$")
    if [ -z "$PROJ_PATH" ]; then
        PROJ_UID="$(new_uid)"
        PROJ_PATH="$PROJ_UID-$3"
        while [ -d "$PROJ_PATH" ]; do
            PROJ_UID="$(new_uid)"
            PROJ_PATH="$PROJ_UID-$3"
        done
        mkdir "$PROJ_PATH"
    fi

    echo "$PROJ_PATH"

elif [ "$1" = "init" ]; then

    cd $2

    GIT_FOLDER="$(pwd)/$3.git"
    if [ -n "$GIT_FOLDER" ]; then
        git init --bare "$GIT_FOLDER"
        cp $POST_RECEIVE "$GIT_FOLDER/hooks/post-receive"
        chmod +x "$GIT_FOLDER/hooks/post-receive"
    fi

else
    usage "Unrecognized command $1"
fi
