#! /bin/bash

ME=`basename "$0"`

usage () {
    echo "Usage: $ME <command> [opts]"
    echo "  $ME init"
    echo ""
    echo "$1"
    exit 1
}

REMOTE="root@minimill"
REPOS_FOLDER="~/git"

if [ $# -ne 1 ]; then
    usage 'Wrong number of arguments..'
fi

if [ "$1" = "init" ]; then

    PROJECT_NAME=${PWD##*/}

    ssh $REMOTE "bash -ic 'cerberus-remote init $REPOS_FOLDER $PROJECT_NAME'"

    git remote remove deploy
    git remote add deploy "$REMOTE:$REPOS_FOLDER/$PROJECT_NAME.git"

    echo "Deploy with 'git push deploy'"

else
    usage "Invalid command $1"
fi
